### PR TITLE
Lbaker/zanecodes connection user

### LINKED ISSUE #1559: Azure PostgreSQL <username@hostname> Not Supported
## Expected Behavior
I expect to be able to configure my `chef-server.rb` file to use an external PostgreSQL database as outlined in Chef documentation like so:

```
postgresql['db_superuser'] = 'chefadmin@azurechefhost' # Postgres user you created
postgresql['db_superuser_password'] = 'somepw' # That user's password
postgresql['external'] = true # Must be set to true
postgresql['port'] = 5432 # Only required if you change the default port
postgresql['vip'] = 'azurechefhost.postgres.database.azure.com' # DNS entry from Azure
```
And then be able to run `chef-server-ctl` reconfigure on a new Chef Server installation to configure my new Chef Server instance to talk to my Azure PostgreSQL backend. This should result in a successful Chef Server configuration/deployment.

## Current Behavior
The current results are not as expected however. Due to the fact that Azure PostgreSQL requires all usernames to be in the format `<username@hostname>`, apparently Ruby code that reads the `postgresql['db_superuser']` entry doesn't interpret the `@` symbol properly and thus doesn't authenticate and perform the install, here is the full error stack:

```
[root@centoschef opscode]# chef-server-ctl reconfigure
Starting Chef Client, version 12.21.31
resolving cookbooks for run list: ["private-chef::default"]
Synchronizing Cookbooks:
  - private-chef (0.1.1)
  - openssl (8.1.2)
  - enterprise (0.11.0)
  - runit (4.0.4)
  - yum-epel (2.1.2)
  - compat_resource (12.19.1)
  - packagecloud (0.3.0)
Installing Cookbook Gems:
Compiling Cookbooks...
/var/opt/opscode/local-mode-cache/cookbooks/packagecloud/resources/repo.rb:10: warning: constant ::Fixnum is deprecated
Recipe: private-chef::default
  * directory[/etc/opscode] action create (up to date)
  * directory[/etc/opscode/logrotate.d] action create (up to date)
[2018-08-23T14:39:36+00:00] FATAL:

-----------------------------------------------------------------------
CSPG999: FATAL:  Invalid Username specified. Please check the Username and retry connection. The Username should be in <username@hostname> format.
FATAL:  Invalid Username specified. Please check the Username and retry connection. The Username should be in <username@hostname> format.
-----------------------------------------------------------------------
```

## Steps to Reproduce (for bugs)

1. Start with a fresh Azure PostgreSQL DB and fresh Centos 7.4 VM.
2. Edit your `chef-server.rb` file as shown in the example above to match your AzurePostgreSQL settings.
3. Run `chef-server-ctl reconfigure` to setup your Chef Server, and you will get the shown results.

## Your Environment
* Chef Server Version: 12.21.31
* Total/free RAM and disk space: 8GB/20GB (Test Server)
* Operating System and Version: Centos 7.4 w/Updates
* If upgrading, previous Chef Server version: N/A
* Running in a container? No (Azure)

### PR DESCRIPTION
**Pull request by lbakerchef**
### Description

This change allows Chef to optionally use a different username for establishing database connections than is used within database queries. This is necessary when using Azure PostgreSQL as an external database.

We would like to thank https://github.com/zanecodes for their contributions to this effort.

### Issues Resolved

#1559

### Task Outline

- [X] Conduct preliminary investigation and testing, identify what is broken and where.
- [X] Procure Azure account and access.
- [X] Investigate Azure VM and database setup.
- [X] Setup development environment to make it conducive for this and future Azure work.
- [X] Investigate configuration settings.
- [X] Fix issues identified in preliminary investigation.  In particular:
- Fix `chef-server-ctl psql...` connection to use <username@hostname> format.
- Fix `psql: FATAL:  password authentication failed for user ...` for internal postgresql setup.
- Change URI format in make_connection_string to create a correctly parseable connection URI (`bad URI` error in external azure postgresql setup).
- [X] Add sql_connection_user attribute for each service to permit a different username to be used for DB connection vs DB queries.
- [X] Replace uses of sql_user and db_superuser for establishing PostgreSQL connections with corresponding connection_user attribute.
- [X] Fix private-chef preflight postgres checks to allow Azure-specific error.
- [X] Update chef-server-ctl to support differing connection and database user names.
- [X] Add ChefSpec test for Azure PostgreSQL connection validation.
- [x] Conduct 'final pass' testing for particular chef-server setups (internal postgresql, external postgresql, external postgresql on Azure, SSL=on and SSL=off modes).
- [x] Generate user documentation.
https://github.com/chef/chef-web-docs/blob/lbakerchef/server_overview1/chef_master/source/server_overview.rst.
- [x] Investigate adding `sql_ro_connection_user` (see 'Tasks Remaining...' below)
- [x] Verify pipeline green
https://buildkite.com/chef/chef-chef-server-master-verify/builds/586
- [x] adhoc pipeline green
https://buildkite.com/chef/chef-chef-server-master-omnibus-adhoc/builds/541#2abd23f0-104e-41ac-bc65-3a3efde6e50b
- [x] Local build
- [x] Speak with Natham Hames and/or Will Fisher regarding use cases in `chef-server-ctl psql ...`
- [x] Make whatever changes after doing step #1
- [x] Place documentation in Vagrantfile or other regarding dev env changes and usage
- [x] Test Tiered without ssl (not with External/Azure enabled) - thanks @christopher-snapp 
- [x] Test HA (with chef-backend, External/Azure not enabled)

### Preliminary Investigation

**Build/Install**

Kitchen + Ad hoc builds: YES
Local install: YES

**Internal PostgreSQL**

`chef-server-ctl reconfigure` PASSES
`chef-server-ctl test` SSL=off PASSES
<s>`chef-server-ctl test` SSL=on</s> N/A (SSL Internal PostgreSQL incomplete)
<s>`chef-server-ctl psql ...` FAILS</s> FIXED

**External PostgreSQL**

`chef-server-ctl reconfigure` PASSES
`chef-server-ctl test` SSL=off PASSES
`chef-server-ctl test` SSL=on PASSES
<s>`chef-server-ctl psql ...` FAILS</s> FIXED

### External Azure PostgreSQL

investigate deployment/setup/config:  DONE
<s>`chef-server-ctl reconfigure` FAILS</s> FIXED
<s>`chef-server-ctl test` SSL=off FAILS</s> FIXED
<s>`chef-server-ctl test` SSL=on FAILS</s> FIXED
<s>`chef-server-ctl psql ...` FAILS</s> FIXED
<s>various connections failing</s>  FIXED

### Configuration Settings Investigation

Completed

### Dev Environment Modifications

Completed

### Final Pass

**internal postgres ssl=off**

`chef-server-ctl reconfigure` PASSED
`chef-server-ctl test` PASSED
`chef-server-ctl psql ...` PASSED
`chef-server-ctl status` PASSED
`chef-server-ctl list-server-admins` PASSED
`chef-server-ctl cleanup-bifrost` PASSED

**external postgres ssl=off**

`chef-server-ctl reconfigure` PASSED
`chef-server-ctl test` PASSED
`chef-server-ctl psql ...` PASSED
`chef-server-ctl status` PASSED
`chef-server-ctl list-server-admins` PASSED
`chef-server-ctl cleanup-bifrost` PASSED

**external postgres ssl=on**

`chef-server-ctl reconfigure` PASSED
`chef-server-ctl test` PASSED
`chef-server-ctl psql ...` PASSED
`chef-server-ctl status` PASSED
`chef-server-ctl list-server-admins` PASSED
`chef-server-ctl cleanup-bifrost` PASSED

**external postgres azure local chef-server ssl=off**

`chef-server-ctl reconfigure` PASSED
`chef-server-ctl test` PASSED
`chef-server-ctl psql ...` PASSED
`chef-server-ctl status` PASSED
`chef-server-ctl list-server-admins` PASSED
`chef-server-ctl cleanup-bifrost` PASSED

**external postgres azure local chef-server ssl=on**

`chef-server-ctl reconfigure` PASSED
`chef-server-ctl test` PASSED
`chef-server-ctl psql ...` PASSED
`chef-server-ctl status` PASSED
`chef-server-ctl list-server-admins` PASSED
`chef-server-ctl cleanup-bifrost` PASSED

### User Manual / Instructions

Finished

### CODE REVIEW

**Comment by lbakerchef** [comment]
https://buildkite.com/chef/chef-chef-server-master-verify/builds/418

File: src/chef-server-ctl/plugins/psql.rb [hunk 1]
```diff
@@ -62,21 +61,26 @@
...
-    db_username=cfg['db_superuser']
-    db_password=credentials.get('postgresql', 'db_superuser_password')
+    db_username = cfg['db_connection_superuser'] || cfg['db_superuser']
+    db_password = credentials.get('postgresql', 'db_superuser_password')
   else
-    db_username=db_config[seed][db_hash_key]["sql_#{ro}user"]
+    if ARGV.include?(write_arg)
+      db_username = db_config[seed][db_hash_key]['sql_connection_user'] || db_config[seed][db_hash_key]['sql_user']
+    else
+      db_username = db_config[seed][db_hash_key]['sql_connection_user'] || db_config[seed][db_hash_key]['sql_ro_user']
```
Comment (PrajaktaPurohit) [inline src/chef-server-ctl/plugins/psql.rb]: At this point the user is trying to connect to the db as a readonly user. Do not think we need to add db_config[seed][db_hash_key]['sql_connection_user'] string here.

Do we need to create another `sql_connection_user_ro` for this purpose?

**Comment by lbakerchef** [comment]
https://buildkite.com/chef/chef-chef-server-master-verify/builds/418

File: src/chef-server-ctl/plugins/psql.rb (hunk 1 above)
Comment (lbakerchef) [reply src/chef-server-ctl/plugins/psql.rb]: POSSIBLE OPTIONS:

1) Put instructions to the user in a source code comment advising how to invoke `psql` and under what conditions.

2) Create an `sql_ro_connection_user`.

3) Proceed with current modifications 'as-is.'

**Comment by markan** [comment]
Re: QUESTION: Do we need to test HA and Tiered setups?
Not with Azure external sql option on; we don't support those topologies with Azure. We should of course make sure that we've not broken those topologies in the default case w/o these changes.

File: src/chef-server-ctl/plugins/psql.rb [hunk 2]
```diff
@@ -62,25 +61,36 @@
...
+  db_name = known_dbs[service_name]["dbname"]
 
   # undocumented, but available. Intended for use primarily for
   # gather-logs to be able to do its thing correctly.
   if (ARGV.include? "--as-admin")
     cfg = running_service_config('postgresql')
-    db_username=cfg['db_superuser']
-    db_password=credentials.get('postgresql', 'db_superuser_password')
+    db_username = cfg['db_connection_superuser'] || cfg['db_superuser']
+    db_password_string = 'db_superuser_password'
```
Comment (markan) [inline src/chef-server-ctl/plugins/psql.rb]: As we talked about in the review, it would be worth it to try and simplify our use cases here; can we reduce it to one or two modes (e.g. admin, and per database user (oc_erchef)

**Comment by PrajaktaPurohit** [comment]
https://buildkite.com/chef/chef-chef-server-master-omnibus-adhoc/builds/622#19bfab64-6214-459e-947b-bfd8e3d91226

**Comment by christopher-snapp** [comment]
I've run the `omnibus-tiered-fresh-install` terraform scenario successfully against this branch after doing some of my own testing against an Azure instance.

**Comment by markan** [comment]
@christopher-snapp That's awesome news! 

@lbakerchef  What remains to be done to get this merged in?

**Comment by lbakerchef** [comment]
Thanks.

File: src/chef-server-ctl/plugins/psql.rb (hunk 1 above)
Comment (lbakerchef) [reply src/chef-server-ctl/plugins/psql.rb]: I went a 4th way (a variation of #2 above).  If it needs a readonly user it uses the existing one (/w associated password).  If it needs an azure connection it adds the associated connection info into the connection string e.g. sql_ro_user@azure_ip.whatever.com.  If it doesn't need an azure connection, it doesn't add the associated garbage into the connection string.

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-backend/commit/7a065c0a0b4afffad6437a2c02cc5217d484a6a5 builds https://buildkite.com/chef/chef-chef-backend-master-omnibus-release/builds/14#fd42ff74-9d2d-49fa-a201-a81d34e32c67 This tests the latest chef-backend with a package containing changes from this PR. Compat with check-backend looks good!

File: src/chef-server-ctl/plugins/psql.rb (hunk 1 above)
Comment (lbakerchef) [reply src/chef-server-ctl/plugins/psql.rb]: See test results on this somewhere below.

**Comment by lbakerchef** [comment]
latest testing of the psql fix, local chef-server, azure postgresql:

```
root@api:~# chef-server-ctl psql opscode_chef
psql (9.6.15)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

opscode_chef=> \q
root@api:~# chef-server-ctl psql opscode_chef --as-admin
psql (9.6.15)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

opscode_chef=> \q
root@api:~# chef-server-ctl psql opscode_chef --write
psql (9.6.15)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

opscode_chef=> \q
root@api:~# chef-server-ctl psql opscode_chef --debug
Host: pr1729.postgres.database.azure.com
Port: 5432
Username: opscode_chef_ro@pr1729.postgres.database.azure.com
Password: a05e2f221c01783e30b9f354c2d90d12455a6799eb659bf404bc315d1e36
DBName: opscode_chef
psql (9.6.15)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

opscode_chef=> \q
root@api:~# chef-server-ctl psql opscode_chef --debug --as-admin
Host: pr1729.postgres.database.azure.com
Port: 5432
Username: opscode_pgsql@pr1729.postgres.database.azure.com
Password: Iluvd3v0ps!
DBName: opscode_chef
psql (9.6.15)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

opscode_chef=> \q
root@api:~# chef-server-ctl psql opscode_chef --debug --write
Host: pr1729.postgres.database.azure.com
Port: 5432
Username: opscode_chef@pr1729.postgres.database.azure.com
Password: 9372ddcbb09ba3c43fb2a5d56d94efcb813a71fc37a0d11b756ddb593857
DBName: opscode_chef
psql (9.6.15)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

opscode_chef=> \q
```

File: src/chef-server-ctl/plugins/psql.rb (hunk 2 above)
Comment (lbakerchef) [reply src/chef-server-ctl/plugins/psql.rb]: Can discuss findings in the next review.

**Comment by danielcbright** [comment]
@PrajaktaPurohit @markan it looks like we're moving along pretty nicely here, any ETA on when these changes will be merged?

**Comment by PrajaktaPurohit** [comment]
@danielcbright we did find some issues due to which these changes were not included in the recent release. We have pushed up some fixes for those. The new changes are in the process of being tested. We are actively working on getting these changes merged. 
My apologies for the delay in getting them in.

**Comment by lbakerchef** [comment]
zanecodes-tests

**Comment by lbakerchef** [comment]
I 'foxed the box' or 'tricked out' the chef-server into thinking it was talking to an Azure PostgreSQL, when in reality it was talking to various locally-installed PostgreSQL scenarios.  I did this to try to tease-out whether errors might be coming from Azure or test environments vs. something in the code itself.  No errors.  Here's a crude diagram explaining what I did, and some text of a report.

zanecodes-tests

```
$ chef-server-ctl test -J pedant.xml --all --compliance-proxy-tests

[SNIP]

Finished in 19 minutes 9 seconds (files took 3.54 seconds to load)
5177 examples, 0 failures, 132 pending

[2019-12-16 19:55:32] INFO  going to shutdown ...
[2019-12-16 19:55:32] INFO  WEBrick::HTTPServer#start done.
root@api:~#
```

**Comment by lbakerchef** [comment]
current rebased branch is: lbaker/zanecodes-connection-user-final

**Comment by PrajaktaPurohit** [comment]
Tested these changes with:
- External postgres in Azure using Postgres as a service in Azure (with ssl enabled and disabled)
- External postgres in Azure using another machine with postgres installed on Azure
- Chef-backend
- Chef-infra-server tiered install
- External postgres in aws (with ssl enabled and disabled)
- Ensured chef-server-ctl psql commands are working as expected
And they all look good.
