### PR TITLE
zei/major versions constraint/1576

### LINKED ISSUE #1576: [erchef] Invalid version constraint when specifying a major platform version
Seems like we can't use a major version in the version constraint of the `supports` section in `metadata.rb`.
 - `supports 'debian', '>= 7.0'` - OK
 - `supports 'debian', '>= 7'` - Error

## Expected Behavior
erchef accepts the PUT request to upload a new cookbook

## Current Behavior
erchef returns 400 with the following message:
```
2018-09-18T13:41:59Z erchef@127.0.0.1 method=PUT; path=/organizations/zuzuzu/cookbooks/zuzuzu_apache/0.2.8; status=400; req_id=g3IAA2QAEGVyY2hlZkAxMjcuMC4wLjEBAAMK+w0EAAEAAAAA; org_name=zuzuzu; msg={ej_invalid,object_value,<<"metadata.platforms">>,<<">= 7">>,string,string,<<"Invalid version constraint">>}; couchdb_groups=false; couchdb_organizations=false; couchdb_containers=false; couchdb_acls=false; 503_mode=false; couchdb_associations=false; couchdb_association_requests=false; req_time=1; rdbms_time=0; rdbms_count=1; user=acondrat; req_api_version=0;
```
## Steps to Reproduce (for bugs)

1. Create a new cookbook
2. Add `supports 'debian', '>= 7'` to it's metadata.rb
3. Try to publish the cookbook to chef-server (ex: using berks upload or knife)

## Your Environment
* Chef Server Version: 12.21.12
* Total/free RAM and disk space: N/A
* Operating System and Version: CentOS Linux release 7.3.1611
* If upgrading, previous Chef Server version: N/A
* Running in a container? No

### PR DESCRIPTION
**Pull request by vinay-satish**
Signed-off-by: Vinay Satish <vinay.satish@progress.com>

### Description

Fixing the validation for version given in the `metadata.rb` while uploading the cookbook.

### Issues Resolved

resolves #1576

### Check List

- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass

### CODE REVIEW

File: src/chef-mover/apps/chef_objects/test/chef_cookbook_version_tests.erl [hunk 1]
```diff
@@ -242,9 +244,7 @@ parse_version_test_() ->
 
 parse_version_badversion_test_() ->
     BadVersions = [
-                   <<"0">>,
-                   <<"1">>,
-                   <<?MAX_GOOD_VERSION>>,
+                   <<?BAD_POSITIVE_VERSION>>,
```
Comment (PrajaktaPurohit) [inline src/chef-mover/apps/chef_objects/test/chef_cookbook_version_tests.erl:247]: nice!

**Review by PrajaktaPurohit — APPROVED** [review]
Looks great! Thank you!

**Comment by tas50** [comment]
We should make sure to call this one out in the release notes. It's an annoying bug that I had to create a cookstyle rule for
